name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linux-build:
    name: Linux Build
    runs-on: [self-hosted, Linux]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: CMake configure -- Release
        run: cmake -S . -G Ninja -B cmake-build-release -DCMAKE_BUILD_TYPE=Release

      - name: CMake build -- Release
        run: cmake --build cmake-build-release -- -j2

      - name: Run tests -- Release
        run: |
          cd cmake-build-release
          ctest
          cd ..

  macos-build:
    name: macOS Build
    runs-on: [self-hosted, macOS]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: CMake configure -- Release
        run: cmake -S . -G Ninja -B cmake-build-release -DCMAKE_BUILD_TYPE=Release

      - name: CMake build -- Release
        run: cmake --build cmake-build-release -- -j4

      - name: Run tests -- Release
        run: |
          cd cmake-build-release
          ctest
          cd ..

  windows-build:
    name: Windows Build
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install conan
          conan --version

      - name: CMake configure -- Release
        run: cmake -S . -B cmake-build-release -DCMAKE_BUILD_TYPE=Release

      - name: CMake build -- Release
        run: cmake --build cmake-build-release --config "Release"

      - name: Run tests -- Release
        run: |
          cd cmake-build-release
          ctest -C Release
          cd ..
